Config = Config or {}

Config.Houses = {}

Config.Furniture = {
	["sofas"] = {
		label = "Дивани",
		items = {
			[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 50, ["label"] = "Стар диван" },
			[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 50, ["label"] = "Триместна пейка" },
			[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 50, ["label"] = "стар стол" },
			[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 50, ["label"] = "Стар триместен диван" },
			[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 50, ["label"] = "Стар диван на райета" },
			[6] = { ["object"] = "v_res_d_armchair", ["price"] = 50, ["label"] = "Стар жълт диван" },
			[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 50, ["label"] = "Ъглов диван" },
			[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 50, ["label"] = "Ъглов диван 2" },
			[9] = { ["object"] = "v_res_d_sofa", ["price"] = 50, ["label"] = "Диван 1" },
			[10] = { ["object"] = "v_res_j_sofa", ["price"] = 50, ["label"] = "Диван 2" },
			[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 50, ["label"] = "Диван 3" },
			[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 50, ["label"] = "Диван 4" },
			[13] = { ["object"] = "v_res_r_sofa", ["price"] = 50, ["label"] = "Диван 5" },
			[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 50, ["label"] = "Диван 6" },
			[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 50, ["label"] = "Диван 7" },
			[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 50, ["label"] = "Диван 8" },
			[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 50, ["label"] = "Диван 9" },
			[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 50, ["label"] = "Диван 10" },
			[19] = { ["object"] = "prop_rub_couch02", ["price"] = 50, ["label"] = "Диван 11" },
			[20] = { ["object"] = "v_ilev_m_sofa", ["price"] = 50, ["label"] = "Бял диван" },
			[21] = { ["object"] = "v_med_p_sofa", ["price"] = 50, ["label"] = "Кожен диван кафяв" },
			[22] = { ["object"] = "v_club_officesofa", ["price"] = 50, ["label"] = "Нисък диван червен" },
			[23] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 50, ["label"] = "Черен диван" },
			[24] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 50, ["label"] = "Ъглов диван 3" },
			[25] = { ["object"] = "prop_couch_lg_02", ["price"] = 50, ["label"] = "Диван загубих бройката" },
			[26] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 50, ["label"] = "Ъглов диван 4" },
			[27] = { ["object"] = "apa_mp_h_yacht_sofa_02", ["price"] = 50, ["label"] = "Кафяв диван" },
			[28] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 50, ["label"] = "Бял дълъг диван" }
		},
	},
	["chairs"] = {
		label = "Столове",
		items = {
			[1] = { ["object"] = "v_res_d_highchair", ["price"] = 50, ["label"] = "Висок стол" },
			[2] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 50, ["label"] = "Седалка 4" },
			[3] = { ["object"] = "v_res_fa_chair01", ["price"] = 50, ["label"] = "Стол 1" },
			[4] = { ["object"] = "v_res_fa_chair02", ["price"] = 50, ["label"] = "Стол 2" },
			[5] = { ["object"] = "v_res_fh_barcchair", ["price"] = 50, ["label"] = "Висок стол 2" },
			[6] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 50, ["label"] = "Кухненски стол 1" },
			[7] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 50, ["label"] = "Кухненски стол 2" },
			[8] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 50, ["label"] = "Кухненски стол 3" },
			[9] = { ["object"] = "v_res_fh_easychair", ["price"] = 50, ["label"] = "Стол 3" },
			[10] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 50, ["label"] = "Стол 4" },
			[11] = { ["object"] = "v_res_fh_singleseat", ["price"] = 50, ["label"] = "Висок стол 3" },
			[12] = { ["object"] = "v_res_jarmchair", ["price"] = 50, ["label"] = "Фотьойл" },
			[13] = { ["object"] = "v_res_j_dinechair", ["price"] = 50, ["label"] = "Кухненски стол 4" },
			[14] = { ["object"] = "v_res_j_stool", ["price"] = 50, ["label"] = "Стол 5" },
			[15] = { ["object"] = "v_res_mbchair", ["price"] = 50, ["label"] = "MB Стол" },
			[16] = { ["object"] = "v_res_m_armchair", ["price"] = 50, ["label"] = "Фотьойл 2" },
			[17] = { ["object"] = "v_res_m_dinechair", ["price"] = 50, ["label"] = "Кухненски стол 5" },
			[18] = { ["object"] = "v_res_study_chair", ["price"] = 50, ["label"] = "Учебен стол" },
			[19] = { ["object"] = "v_res_trev_framechair", ["price"] = 50, ["label"] = "Рамка на стол" },
			[20] = { ["object"] = "v_res_tre_chair", ["price"] = 50, ["label"] = "Стол 5" },
			[21] = { ["object"] = "v_res_tre_officechair", ["price"] = 50, ["label"] = "Офис стол" },
			[22] = { ["object"] = "v_res_tre_stool", ["price"] = 50, ["label"] = "Стол 6" },
			[23] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 50, ["label"] = "Кожен стол" },
			[24] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 50, ["label"] = "Стол Scuz" },
			[25] = { ["object"] = "v_med_p_deskchair", ["price"] = 50, ["label"] = "Офис стол" },
			[26] = { ["object"] = "v_med_p_easychair", ["price"] = 50, ["label"] = "Kресло" },
			[27] = { ["object"] = "v_med_whickerchair1", ["price"] = 50, ["label"] = "Уикер стол" },
			[28] = { ["object"] = "prop_direct_chair_01", ["price"] = 50, ["label"] = "Директорски стол" },
			[29] = { ["object"] = "prop_direct_chair_02", ["price"] = 50, ["label"] = "Директорски стол 2" },
			[30] = { ["object"] = "prop_yacht_lounger", ["price"] = 50, ["label"] = "Плетен стол 1" },
			[31] = { ["object"] = "prop_yacht_seat_01", ["price"] = 50, ["label"] = "Плетен стол 2" },
			[32] = { ["object"] = "prop_yacht_seat_02", ["price"] = 50, ["label"] = "Плетен стол 3" },
			[33] = { ["object"] = "prop_yacht_seat_03", ["price"] = 50, ["label"] = "Плетен стол 4" },
			[34] = { ["object"] = "v_ret_chair_white", ["price"] = 50, ["label"] = "Бял стол" },
			[35] = { ["object"] = "v_ret_chair", ["price"] = 50, ["label"] = "Стол 7" },
			[36] = { ["object"] = "v_ret_ta_stool", ["price"] = 50, ["label"] = "TA Стол" },
			[37] = { ["object"] = "prop_cs_office_chair", ["price"] = 50, ["label"] = "Офис стол 2" },
			[38] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 50, ["label"] = "Бял фотьойл" },
			[39] = { ["object"] = "v_club_barchair", ["price"] = 50, ["label"] = "Стол 8" },
			[40] = { ["object"] = "prop_off_chair_04", ["price"] = 50, ["label"] = "Офис стол 2" },
			[41] = { ["object"] = "v_club_stagechair", ["price"] = 50, ["label"] = "Фотьойл розов" },
			[42] = { ["object"] = "v_club_officechair", ["price"] = 50, ["label"] = "Офис стол 3" },
			[43] = { ["object"] = "prop_armchair_01", ["price"] = 50, ["label"] = "Стол 9" },
			[44] = { ["object"] = "prop_bar_stool_01", ["price"] = 50, ["label"] = "Бар стол" },
			[45] = { ["object"] = "apa_mp_h_yacht_stool_01", ["price"] = 50, ["label"] = "Бял пуф" },
			[46] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 50, ["label"] = "Стол 10 3" },
			[47] = { ["object"] = "apa_mp_h_stn_chairstool_12", ["price"] = 50, ["label"] = "Подложка за крака" },
			[48] = { ["object"] = "v_ret_gc_chair01", ["price"] = 50, ["label"] = "GC Стол 01" },
			[49] = { ["object"] = "v_ret_gc_chair02", ["price"] = 50, ["label"] = "GC Стол 02" },
			[50] = { ["object"] = "prop_chair_03", ["price"] = 50, ["label"] = "Дървен стол" }
		},
	},
	["beds"] = {
		label = "Легла",
		items = {
			[1] = { ["object"] = "v_res_d_bed", ["price"] = 50, ["label"] = "Оранжево легло" },	
			[2] = { ["object"] = "v_res_lestersbed", ["price"] = 50, ["label"] = "Дървено легло малко" },	
			[3] = { ["object"] = "v_res_mbbed", ["price"] = 50, ["label"] = "Класическо легло кафяво" },	
			[4] = { ["object"] = "v_res_mdbed", ["price"] = 50, ["label"] = "Класическо легло бяло" },	
			[5] = { ["object"] = "v_res_msonbed", ["price"] = 50, ["label"] = "Кожено легло" },	
			[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 50, ["label"] = "Дървено легло зелено" },	
			[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 50, ["label"] = "Дървено легло синьо" },	
			[8] = { ["object"] = "v_res_tt_bed", ["price"] = 50, ["label"] = "Мръсно легло" },
			[9] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 50, ["label"] = "Модерно легло" },
			[10] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 50, ["label"] = "Червено легло" },
			[11] = { ["object"] = "bkr_prop_biker_campbed_01", ["price"] = 50, ["label"] = "Лагерно легло" },
			[12] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 50, ["label"] = "Възглавница 1" },
			[13] = { ["object"] = "v_res_tre_cushiona", ["price"] = 50, ["label"] = "Възглавница 2" },
			[14] = { ["object"] = "v_res_tre_cushionb", ["price"] = 50, ["label"] = "Възглавница 3" },
			[15] = { ["object"] = "v_res_tre_cushionc", ["price"] = 50, ["label"] = "Възглавница 4" },
			[16] = { ["object"] = "v_res_tre_cushiond", ["price"] = 50, ["label"] = "Възглавница 5" },
			[17] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 50, ["label"] = "Възглавница 6" },
			[18] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 50, ["label"] = "Възглавница 7" }
		},	
	},
	["general"] = {
		label = "Разни работи",
		items = {
			[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 50, ["label"] = "Барбарон" },
			[2] = { ["object"] = "v_res_cherubvase", ["price"] = 50, ["label"] = "Бяла ваза" },
			[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 50, ["label"] = "Подплатена стена" },
			[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 50, ["label"] = "Череп" },
			[5] = { ["object"] = "v_res_d_whips", ["price"] = 50, ["label"] = "Kамшици" },
			[6] = { ["object"] = "v_res_fashmag1", ["price"] = 50, ["label"] = "Списание" },
			[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 50, ["label"] = "Списание 1" },
			[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 50, ["label"] = "Списание 2" },
			[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 50, ["label"] = "Постелка за йога 1" },
			[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 50, ["label"] = "Постелка за йога 2" },
			[11] = { ["object"] = "prop_yoga_mat_01", ["price"] = 50, ["label"] = "Постелка за йога 1" },
			[12] = { ["object"] = "prop_yoga_mat_02", ["price"] = 50, ["label"] = "Постелка за йога 2" },
			[13] = { ["object"] = "prop_yoga_mat_03", ["price"] = 50, ["label"] = "Постелка за йога 3" },
			[14] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 50, ["label"] = "Aftershave" },
			[15] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 50, ["label"] = "Кошница за плодове" },
			[16] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 50, ["label"] = "Панер за пране" },
			[17] = { ["object"] = "v_res_fh_pouf", ["price"] = 50, ["label"] = "Пуф" },
			[18] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 50, ["label"] = "Скулптура" },
			[19] = { ["object"] = "v_res_j_magrack", ["price"] = 50, ["label"] = "Кошница за списания 2" },
			[20] = { ["object"] = "v_res_jewelbox", ["price"] = 50, ["label"] = "Кутия за бижута" },
			[21] = { ["object"] = "v_res_mbbin", ["price"] = 50, ["label"] = "Кошове за пране" },
			[22] = { ["object"] = "v_res_mbowlornate", ["price"] = 50, ["label"] = "Купа с плодове" },
			[23] = { ["object"] = "v_res_mbronzvase", ["price"] = 50, ["label"] = "Бронзова ваза" },
			[24] = { ["object"] = "v_res_mchalkbrd", ["price"] = 50, ["label"] = "Дъска" },
			[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 50, ["label"] = "Пепелник син" },
			[26] = { ["object"] = "prop_ashtray_01", ["price"] = 50, ["label"] = "Пепелник черен" },
			[27] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 50, ["label"] = "Пепелник" },
			[28] = { ["object"] = "v_res_m_kscales", ["price"] = 50, ["label"] = "Везна" },
			[29] = { ["object"] = "v_med_cor_whiteboard", ["price"] = 50, ["label"] = "Бяла дъска" },
			[30] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 50, ["label"] = "Килим 1" },
			[31] = { ["object"] = "ex_mp_h_acc_rugwoolm_04", ["price"] = 50, ["label"] = "Килим 2" },
			[32] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 50, ["label"] = "Килим 3" },
			[33] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 50, ["label"] = "Килим 4" },
			[34] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 50, ["label"] = "Килим 5" },
			[35] = { ["object"] = "hei_mpheist_yacht_ab_03", ["price"] = 50, ["label"] = "Пиано" },
			[36] = { ["object"] = "prop_printer_01", ["price"] = 50, ["label"] = "Принтер" },
		},
	},
	["general2"] = {
		label = "Обекти",
		items = {
			[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 50, ["label"] = "Купчина A4 1" },
			[2] = { ["object"] = "prop_barry_table_detail", ["price"] = 50, ["label"] = "Купчина A4 2" },
			[3] = { ["object"] = "prop_cs_binder_01", ["price"] = 50, ["label"] = "Папка" },
			[4] = { ["object"] = "v_med_p_notebook", ["price"] = 50, ["label"] = "Бележки" },
			[5] = { ["object"] = "prop_cs_lester_crate", ["price"] = 50, ["label"] = "Кутия с папки" },
			[6] = { ["object"] = "prop_amb_40oz_03", ["price"] = 50, ["label"] = "Бира 1" },
			[7] = { ["object"] = "ba_prop_club_champset", ["price"] = 50, ["label"] = "Комплект шампанско" },
			[8] = { ["object"] = "prop_champ_cool", ["price"] = 50, ["label"] = "Охладител за шампанско" },
			[9] = { ["object"] = "prop_champ_01b", ["price"] = 50, ["label"] = "Бутилка шампанско" },
			[10] = { ["object"] = "prop_champ_flute", ["price"] = 50, ["label"] = "Чаша за шампанско" },
			[11] = { ["object"] = "prop_cs_champ_flute", ["price"] = 50, ["label"] = "Чаша със шампанско" },
			[12] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 50, ["label"] = "Бутилка уиски" },
			[13] = { ["object"] = "prop_tumbler_01", ["price"] = 50, ["label"] = "Чаша за уиски" },
			[14] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 50, ["label"] = "Бира 2" },
			[15] = { ["object"] = "prop_beer_box_01", ["price"] = 50, ["label"] = "Стек бира 1" },
			[16] = { ["object"] = "prop_cs_beer_box", ["price"] = 50, ["label"] = "Стек бира 2" },
			[17] = { ["object"] = "prop_binoc_01", ["price"] = 50, ["label"] = "Бинокъл" },
			[18] = { ["object"] = "prop_blox_spray", ["price"] = 50, ["label"] = "Препарат за чистене" },
			[19] = { ["object"] = "prop_bongos_01", ["price"] = 50, ["label"] = "Бонгос" },
			[20] = { ["object"] = "prop_bong_01", ["price"] = 50, ["label"] = "Бонг 1" },
			[21] = { ["object"] = "prop_boombox_01", ["price"] = 50, ["label"] = "Бумбос" },
			[22] = { ["object"] = "prop_bowl_crisps", ["price"] = 50, ["label"] = "Купа с чипс" },
			[23] = { ["object"] = "prop_candy_pqs", ["price"] = 50, ["label"] = "Кутия със сладки" },
			[24] = { ["object"] = "prop_carrier_bag_01", ["price"] = 50, ["label"] = "Пазарска чанта" },
			[25] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 50, ["label"] = "Плик с Бъргършот" },
			[26] = { ["object"] = "prop_cs_sack_01", ["price"] = 50, ["label"] = "Чувал" },
			[27] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 50, ["label"] = "Торба за смет" },
			[28] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 50, ["label"] = "Керамична кана" },
			[29] = { ["object"] = "prop_cigar_pack_01", ["price"] = 50, ["label"] = "Кутия с цигари 1" },
			[30] = { ["object"] = "prop_cigar_pack_02", ["price"] = 50, ["label"] = "Кутия с цигари 2" },
			[31] = { ["object"] = "prop_cs_bs_cup", ["price"] = 50, ["label"] = "Напитка от Бъргършот" },
			[32] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 50, ["label"] = "Писмо" },
			[33] = { ["object"] = "prop_cs_duffel_01", ["price"] = 50, ["label"] = "Сак" },
			[34] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["label"] = "DVD" },
			[35] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["label"] = "DVD кейс" },
			[36] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 50, ["label"] = "Филмова макара" },
			[37] = { ["object"] = "prop_cs_ironing_board", ["price"] = 50, ["label"] = "Дъска за гладене" },
			[38] = { ["object"] = "prop_cs_katana_01", ["price"] = 50, ["label"] = "Катана" },
			[39] = { ["object"] = "prop_cs_petrol_can", ["price"] = 50, ["label"] = "Туба с гориво" },
			[40] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 50, ["label"] = "Сироп за кашлица " },
			[41] = { ["object"] = "prop_cs_script_bottle", ["price"] = 50, ["label"] = "Хапчета" },
			[42] = { ["object"] = "prop_sh_bong_01", ["price"] = 50, ["label"] = "Бонг 2" },
			[43] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 50, ["label"] = "Купа с фъстъци" },
			[44] = { ["object"] = "p_cs_lighter_01", ["price"] = 50, ["label"] = "Запалка" },
			[45] = { ["object"] = "p_cs_papers_01", ["price"] = 50, ["label"] = "Листчета за свиване" },
			[46] = { ["object"] = "v_res_m_candle", ["price"] = 50, ["label"] = "Свещ 1" },
			[47] = { ["object"] = "v_res_m_candlelrg", ["price"] = 50, ["label"] = "Свещ 2" },
			[48] = { ["object"] = "v_res_fa_candle01", ["price"] = 50, ["label"] = "Свещ 3" },
			[49] = { ["object"] = "v_res_fa_candle02", ["price"] = 50, ["label"] = "Свещ 4" },
			[50] = { ["object"] = "v_res_fa_candle03", ["price"] = 50, ["label"] = "Свещ 5" },
			[51] = { ["object"] = "v_res_fa_candle04", ["price"] = 50, ["label"] = "Свещ 6" },
			[52] = { ["object"] = "v_med_bottles2", ["price"] = 50, ["label"] = "Туби с химикали" },
			[53] = { ["object"] = "v_res_desktidy", ["price"] = 50, ["label"] = "Канцеларски материали" },
			[54] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 50, ["label"] = "Изсушена трева" },
			[55] = { ["object"] = "ba_prop_battle_trophy_battler", ["price"] = 50, ["label"] = "Трофей 1" },
			[56] = { ["object"] = "ba_prop_battle_trophy_no1", ["price"] = 50, ["label"] = "Трофей 2" },
			[57] = { ["object"] = "prop_golf_bag_01c", ["price"] = 50, ["label"] = "Чанта за голф" },
			[58] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 50, ["label"] = "Кошче за боклук" },
			[59] = { ["object"] = "prop_wooden_barrel", ["price"] = 50, ["label"] = "Бъчва" },
			[60] = { ["object"] = "prop_mb_sandblock_01", ["price"] = 50, ["label"] = "Пясъчен блок x1" },
			[61] = { ["object"] = "prop_mb_sandblock_02", ["price"] = 50, ["label"] = "Пясъчен блок x3" },
			[62] = { ["object"] = "p_pallet_02a_s", ["price"] = 50, ["label"] = "Палет" },
			[63] = { ["object"] = "ch_chint03_pallet_pile_01", ["price"] = 50, ["label"] = "Палети" },
			[64] = { ["object"] = "ex_prop_crate_money_bc", ["price"] = 50, ["label"] = "Сандък с пари" },
			[65] = { ["object"] = "hei_prop_heist_weed_pallet", ["price"] = 50, ["label"] = "Палет с трева" },
			[66] = { ["object"] = "sm_prop_smug_crate_m_narc", ["price"] = 50, ["label"] = "Съндъци с трева" },	
			[67] = { ["object"] = "prop_paints_pallete01", ["price"] = 50, ["label"] = "Палет с бои" },
			[68] = { ["object"] = "ex_prop_crate_art_02_sc", ["price"] = 50, ["label"] = "Палет с картини" },
			[69] = { ["object"] = "sm_prop_smug_crate_m_medical", ["price"] = 50, ["label"] = "Палет с медицински неща " },
			[70] = { ["object"] = "sm_prop_smug_crate_m_tobacco", ["price"] = 50, ["label"] = "Палет с тютюн" },
			[71] = { ["object"] = "sm_prop_smug_crate_s_jewellery", ["price"] = 50, ["label"] = "Сандък с бижута" },
			[72] = { ["object"] = "p_secret_weapon_02", ["price"] = 50, ["label"] = "Сандък с оръжия" },
			[73] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 50, ["label"] = "Купчина с пари 1" },
			[74] = { ["object"] = "bkr_prop_bkr_cashpile_05", ["price"] = 50, ["label"] = "Купчина с пари 2" },
			[75] = { ["object"] = "prop_flattruck_01d", ["price"] = 50, ["label"] = "Количка със съндъци" },
			[76] = { ["object"] = "bkr_int_w03_pallettruck", ["price"] = 50, ["label"] = "Палетна количка" },
			[77] = { ["object"] = "v_55_tor_mesh_forklift", ["price"] = 50, ["label"] = "Мотокар" },
			[78] = { ["object"] = "prop_rub_pile_03", ["price"] = 50, ["label"] = "Гуми за кола" },
			[79] = { ["object"] = "sm_prop_smug_crate_s_jewellery", ["price"] = 50, ["label"] = "Сандък с бижута 2" },
			[80] = { ["object"] = "ex_office_swag_guns02", ["price"] = 50, ["label"] = "Кутия с патрони" },
			[81] = { ["object"] = "v_ilev_fib_door3", ["price"] = 50, ["label"] = "Врата" }
		},
	},
	["general3"] = {
		label = "Random",
		items = {
			[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 50, ["label"] = "Кошче 1" },
			[2] = { ["object"] = "v_ret_gc_bin", ["price"] = 50, ["label"] = "Кошче 2" },
			[3] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 50, ["label"] = "Панер за пране" },
			[4] = { ["object"] = "v_ret_gc_bag01", ["price"] = 50, ["label"] = "Сак 1" },
			[5] = { ["object"] = "v_ret_gc_bag02", ["price"] = 50, ["label"] = "Сак 2" },
			[6] = { ["object"] = "prop_big_bag_01", ["price"] = 50, ["label"] = "Сак 3" },
			[7] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 50, ["label"] = "Каса" },
			[8] = { ["object"] = "v_ret_gc_clock", ["price"] = 50, ["label"] = "Стенен часовник" },
			[9] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 50, ["label"] = "Чанта 1" },
			[10] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 50, ["label"] = "Чанта 2" },
			[11] = { ["object"] = "prop_amb_handbag_01", ["price"] = 50, ["label"] = "Чанта 3" },
			[12] = { ["object"] = "v_ret_ta_book1", ["price"] = 50, ["label"] = "Книга 1" },
			[13] = { ["object"] = "v_ret_ta_book2", ["price"] = 50, ["label"] = "Книга 2" },
			[14] = { ["object"] = "v_ret_ta_book3", ["price"] = 50, ["label"] = "Книга 3" },
			[15] = { ["object"] = "v_ret_ta_book4", ["price"] = 50, ["label"] = "Книга 4" },
			[16] = { ["object"] = "v_res_fa_book03", ["price"] = 50, ["label"] = "Книга 5" },
			[17] = { ["object"] = "v_ret_ta_camera", ["price"] = 50, ["label"] = "Фотоапарат" },
			[18] = { ["object"] = "v_ret_ta_hero", ["price"] = 50, ["label"] = "Фигурка" },
			[19] = { ["object"] = "v_ret_ta_mag1", ["price"] = 50, ["label"] = "Купчина списания 1" },
			[20] = { ["object"] = "v_ret_ta_mag2", ["price"] = 50, ["label"] = "Купчина списания 2" },
			[21] = { ["object"] = "v_ret_ta_skull", ["price"] = 50, ["label"] = "Череп" },
			[22] = { ["object"] = "prop_acc_guitar_01", ["price"] = 50, ["label"] = "Китара 1" },
			[23] = { ["object"] = "prop_el_guitar_01", ["price"] = 50, ["label"] = "Китара 2" },
			[24] = { ["object"] = "prop_el_guitar_02", ["price"] = 50, ["label"] = "Китара 3" },
			[25] = { ["object"] = "prop_el_guitar_03", ["price"] = 50, ["label"] = "Китара 4" },
			[26] = { ["object"] = "prop_attache_case_01", ["price"] = 50, ["label"] = "Отворен куфар" },
			[27] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 50, ["label"] = "Шопинг чанта" },
			[28] = { ["object"] = "prop_cs_vial_01", ["price"] = 50, ["label"] = "Термус" },
			[29] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 50, ["label"] = "Кукла" }, 
			[30] = { ["object"] = "prop_weight_rack_02", ["price"] = 50, ["label"] = "Дъмбели" },
			[31] = { ["object"] = "prop_weight_bench_02", ["price"] = 50, ["label"] = "Лежанка" },
			[32] = { ["object"] = "prop_tool_broom", ["price"] = 50, ["label"] = "Метла" },
			[33] = { ["object"] = "prop_fire_exting_2a", ["price"] = 50, ["label"] = "Пожарогасител" },
			[34] = { ["object"] = "v_res_vacuum", ["price"] = 50, ["label"] = "Прахосмукачка" },
			[35] = { ["object"] = "v_ret_gc_fan", ["price"] = 50, ["label"] = "Вентилатор" },
			[36] = { ["object"] = "prop_paint_stepl01b", ["price"] = 50, ["label"] = "Стълба" },
			[37] = { ["object"] = "bkr_prop_weed_bucket_01b", ["price"] = 50, ["label"] = "Кофа 1" },
			[38] = { ["object"] = "prop_cs_fertilizer", ["price"] = 50, ["label"] = "Варел" },
			[39] = { ["object"] = "v_club_vusnaketank", ["price"] = 50, ["label"] = "Терариум" },
			[40] = { ["object"] = "prop_pooltable_02", ["price"] = 50, ["label"] = "Маса за билярд" },
			[41] = { ["object"] = "prop_pool_rack_02", ["price"] = 50, ["label"] = "Билярдни стикове" },
			[42] = { ["object"] = "v_club_vu_deckcase", ["price"] = 50, ["label"] = "DJ пулт" },
			[43] = { ["object"] = "v_corp_servercln", ["price"] = 50, ["label"] = "Сървърна машина" },
			[44] = { ["object"] = "prop_gold_trolly_full", ["price"] = 50, ["label"] = "Количка със златни кюлчета" }
		},
	},
	["general4"] = {
		label = "Random 2",
		items = {
			[1] = { ["object"] = "prop_dummy_01", ["price"] = 50, ["label"] = "Манекен" },
			[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 50, ["label"] = "Часовник с формата на яйце" },
			[3] = { ["object"] = "prop_feed_sack_01", ["price"] = 50, ["label"] = "Чувал с царевица" },
			[4] = { ["object"] = "prop_floor_duster_01", ["price"] = 50, ["label"] = "Моп 1" },
			[5] = { ["object"] = "prop_f_duster_02", ["price"] = 50, ["label"] = "Моп 2" },
			[6] = { ["object"] = "prop_fruit_basket", ["price"] = 50, ["label"] = "Кошница" },
			[7] = { ["object"] = "prop_grapes_02", ["price"] = 50, ["label"] = "Грозде" },
			[8] = { ["object"] = "prop_idol_case_01", ["price"] = 50, ["label"] = "Дървена кутия" },
			[9] = { ["object"] = "prop_jewel_02a", ["price"] = 50, ["label"] = "Бижута 1" },
			[10] = { ["object"] = "prop_jewel_02b", ["price"] = 50, ["label"] = "Бижута 2" },
			[11] = { ["object"] = "prop_jewel_02c", ["price"] = 50, ["label"] = "Бижута 3" },
			[12] = { ["object"] = "prop_jewel_03a", ["price"] = 50, ["label"] = "Бижута 4" },
			[13] = { ["object"] = "prop_jewel_03b", ["price"] = 50, ["label"] = "Бижута 5" },
			[14] = { ["object"] = "prop_jewel_04a", ["price"] = 50, ["label"] = "Бижута 6" },
			[15] = { ["object"] = "prop_jewel_04b", ["price"] = 50, ["label"] = "Бижута 7" },
			[16] = { ["object"] = "p_watch_01", ["price"] = 50, ["label"] = "Ръчен часовник 1" },
			[17] = { ["object"] = "p_watch_02", ["price"] = 50, ["label"] = "Ръчен часовник 2" },
			[18] = { ["object"] = "p_watch_03", ["price"] = 50, ["label"] = "Ръчен часовник 3" },
			[19] = { ["object"] = "p_watch_04", ["price"] = 50, ["label"] = "Ръчен часовник 4" },
			[20] = { ["object"] = "p_watch_05", ["price"] = 50, ["label"] = "Ръчен часовник 5" },
			[21] = { ["object"] = "p_watch_06", ["price"] = 50, ["label"] = "Ръчен часовник 6" },
			[22] = { ["object"] = "prop_j_disptray_01", ["price"] = 50, ["label"] = "Поднос с бижута 1" },
			[23] = { ["object"] = "prop_j_disptray_01b", ["price"] = 50, ["label"] = "Поднос с бижута 2" },
			[24] = { ["object"] = "prop_j_disptray_02", ["price"] = 50, ["label"] = "Поднос с бижута 3" },
			[25] = { ["object"] = "prop_j_disptray_03", ["price"] = 50, ["label"] = "Поднос с бижута 4" },
			[26] = { ["object"] = "prop_j_disptray_04", ["price"] = 50, ["label"] = "Поднос с бижута 5" },
			[27] = { ["object"] = "prop_j_disptray_04b", ["price"] = 50, ["label"] = "Поднос с бижута 6" },
			[28] = { ["object"] = "prop_j_disptray_05", ["price"] = 50, ["label"] = "Поднос с бижута 7" },
			[29] = { ["object"] = "prop_j_disptray_05b", ["price"] = 50, ["label"] = "Поднос с бижута 8" },
			[30] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 50, ["label"] = "Зелен екран" },
			[31] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 50, ["label"] = "Туба с гориво 1" },
			[32] = { ["object"] = "prop_ld_keypad_01", ["price"] = 50, ["label"] = "Панел за сигурност 1" },
			[33] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 50, ["label"] = "Панел за сигурност 2" },
			[34] = { ["object"] = "v_corp_bk_secpanel", ["price"] = 50, ["label"] = "Панел за сигурност 3" },
			[35] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 50, ["label"] = "Куфар 1" },
			[36] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 50, ["label"] = "Куфар 2" },
			[37] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 50, ["label"] = "Куфар 3"},
			[38] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 50, ["label"] = "Плюшено мече" },
			[39] = { ["object"] = "prop_shopping_bags01", ["price"] = 50, ["label"] = "Шопинг чанти 1" },
			[40] = { ["object"] = "prop_shopping_bags02", ["price"] = 50, ["label"] = "Шопинг чанти 2" },
			[41] = { ["object"] = "p_ld_sax", ["price"] = 50, ["label"] = "Саксофон" },
			[42] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 50, ["label"] = "Футболна топка" }
		},
	},
	["small"] = {
		label = "Детайли",
		items = {
			[1] = { ["object"] = "v_res_r_figcat", ["price"] = 50, ["label"] = "Скулптура на котка" },
			[2] = { ["object"] = "v_res_r_figclown", ["price"] = 50, ["label"] = "Скулптура на клоун" },
			[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 50, ["label"] = "Сертификат в рамка" },
			[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 50, ["label"] = "Скулптура на жена" },
			[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 50, ["label"] = "Скулптура на жена - Фламенко" },
			[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 50, ["label"] = "Скулптура на момиченце" },
			[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 50, ["label"] = "Скулптура на момиченце клоун" },
			[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 50, ["label"] = "Скулптура на обелиск" },
			[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 50, ["label"] = "Скулптура на стълб" },
			[10] = { ["object"] = "v_res_r_teapot", ["price"] = 50, ["label"] = "Чайник" },
			[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 50, ["label"] = "Фигура 1" },
			[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 50, ["label"] = "Фигура 2" },
			[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 50, ["label"] = "Фигура 3" },
			[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 50, ["label"] = "Фигура 4" },
			[15] = { ["object"] = "v_res_skateboard", ["price"] = 50, ["label"] = "Скейтборд" },
			[16] = { ["object"] = "v_res_sketchpad", ["price"] = 50, ["label"] = "Скицпад" },
			[17] = { ["object"] = "v_res_tissues", ["price"] = 50, ["label"] = "Салфетки" },
			[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 50, ["label"] = "Кошница с безполезни неща" },
			[19] = { ["object"] = "v_res_tre_bin", ["price"] = 50, ["label"] = "Кошче за боклук" },
			[20] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 50, ["label"] = "Купа с писма" },
			[21] = { ["object"] = "prop_idol_01", ["price"] = 50, ["label"] = "Фигурка" },
			[22] = { ["object"] = "v_res_r_fighorsestnd", ["price"] = 50, ["label"] = "Фигурка на кон" },
			[23] = { ["object"] = "v_res_r_fighorse", ["price"] = 50, ["label"] = "Фигурка на кон 2" },
			[24] = { ["object"] = "v_res_r_figdancer", ["price"] = 50, ["label"] = "Фигурка на принцеса" },
			[25] = { ["object"] = "v_res_fa_idol02", ["price"] = 50, ["label"] = "Фигурка на слон" },
			[26] = { ["object"] = "v_res_m_statue", ["price"] = 50, ["label"] = "Скулптура 2" },
			[27] = { ["object"] = "v_20_ornaeagle", ["price"] = 50, ["label"] = "Фигурка на орел" },
			[28] = { ["object"] = "v_med_p_vaseround", ["price"] = 50, ["label"] = "Ваза" },
			[29] = { ["object"] = "ex_mp_h_acc_vase_05", ["price"] = 50, ["label"] = "Ваза 2" },
			[30] = { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 50, ["label"] = "Произведение на изкуството 1" },
			[31] = { ["object"] = "apa_mp_h_acc_dec_sculpt_02", ["price"] = 50, ["label"] = "Произведение на изкуството 2" },
			[32] = { ["object"] = "ex_mp_h_acc_dec_plate_02", ["price"] = 50, ["label"] = "Произведение на изкуството 3" },
			[33] = { ["object"] = "apa_mp_h_acc_bowl_ceramic_01", ["price"] = 50, ["label"] = "Керамична купа" }
		},
	},
	["storage"] = {
		label = "Шкафове",
		items = {
			[1] = { ["object"] = "v_res_cabinet", ["price"] = 50, ["label"] = "Шкаф" },
			[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 50, ["label"] = "Тоалетна масичка" },
			[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 50, ["label"] = "Скрин 1" },
			[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 50, ["label"] = "Скрин 2" },
			[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 50, ["label"] = "Скрин 3" },
			[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 50, ["label"] = "Нощно шкафче" },
			[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 50, ["label"] = "Шкафче с телевизор" },
			[8] = { ["object"] = "v_res_mbdresser", ["price"] = 50, ["label"] = "Скрин 4" },
			[9] = { ["object"] = "v_res_mbottoman", ["price"] = 50, ["label"] = "Табуретка" },
			[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 50, ["label"] = "Скрин 5" },
			[11] = { ["object"] = "v_res_mcupboard", ["price"] = 50, ["label"] = "Шкаф 2" },
			[12] = { ["object"] = "v_res_mdchest", ["price"] = 50, ["label"] = "Скрин 6" },
			[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 50, ["label"] = "Шкаф 3" },
			[14] = { ["object"] = "v_res_m_armoire", ["price"] = 50, ["label"] = "Шкаф 4" },
			[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 50, ["label"] = "Масичка с огледало" },
			[16] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 50, ["label"] = "Нощно шкафче 2" },
			[17] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 50, ["label"] = "Нощно шкафче 3" },
			[18] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 50, ["label"] = "Лавица за книги" },
			[19] = { ["object"] = "v_res_tre_storagebox", ["price"] = 50, ["label"] = "Сандък за съхранение" },
			[20] = { ["object"] = "v_res_tre_storageunit", ["price"] = 50, ["label"] = "Скрин 7" },
			[21] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 50, ["label"] = "Гардероб" },
			[22] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 50, ["label"] = "Стар шкаф" },
			[23] = { ["object"] = "prop_devin_box_closed", ["price"] = 50, ["label"] = "Сандък 1" },
			[24] = { ["object"] = "prop_mil_crate_01", ["price"] = 50, ["label"] = "Сандък 2" },
			[25] = { ["object"] = "prop_mil_crate_02", ["price"] = 50, ["label"] = "Сандък 3" },
			[26] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 50, ["label"] = "Сейф" },
			[27] = { ["object"] = "p_devin_box_01_s", ["price"] = 50, ["label"] = "Сандък" },
			[28] = { ["object"] = "v_corp_filecablow", ["price"] = 50, ["label"] = "Офис шкаф 1" },
			[29] = { ["object"] = "v_corp_filecabtall", ["price"] = 50, ["label"] = "Офис шкаф 2" },
			[30] = { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 50, ["label"] = "Шкаф 5" },
			[31] = { ["object"] = "prop_coathook_01", ["price"] = 50, ["label"] = "Закачалки" },
			[32] = { ["object"] = "v_corp_lowcabdark01", ["price"] = 50, ["label"] = "Офис шкаф 3" },
			[33] = { ["object"] = "v_corp_tallcabdark01", ["price"] = 50, ["label"] = "Офис шкаф 4" },
			[34] = { ["object"] = "v_corp_cabshelves01", ["price"] = 50, ["label"] = "Офис шкаф 5" },
			[35] = { ["object"] = "v_corp_offshelf", ["price"] = 50, ["label"] = "Офис шкаф 6" },
			[36] = { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 50, ["label"] = "Модерна табуретка 1" },
			[37] = { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 50, ["label"] = "Модерна табуретка 2" },
			[38] = { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 50, ["label"] = "Стенен шкаф" },
			[39] = { ["object"] = "apa_mp_h_str_sideboardl_11", ["price"] = 50, ["label"] = "Шкаф за обувки" },
			[40] = { ["object"] = "prop_box_wood02a_pu", ["price"] = 50, ["label"] = "Сандък с провизии" },
			[41] = { ["object"] = "prop_mb_cargo_02a", ["price"] = 50, ["label"] = "Карго палет" },
			[42] = { ["object"] = "imp_prop_impexp_rack_01a", ["price"] = 50, ["label"] = "Стелаж 1" },
			[43] = { ["object"] = "imp_prop_impexp_rack_02a", ["price"] = 50, ["label"] = "Стелаж 2" },
			[44] = { ["object"] = "imp_prop_impexp_rack_03a", ["price"] = 50, ["label"] = "Стелаж 3" },
			[45] = { ["object"] = "imp_prop_impexp_rack_04a", ["price"] = 50, ["label"] = "Стелаж 4" },
			[46] = { ["object"] = "prop_rub_cage01b", ["price"] = 50, ["label"] = "Количка с кашони" },
			[47] = { ["object"] = "v_res_mddresser", ["price"] = 50, ["label"] = "Шкаф с огледало 2" },
			[48] = { ["object"] = "v_club_rack", ["price"] = 50, ["label"] = "Подвижна закачалка за дрехи" },
			[49] = { ["object"] = "v_med_p_sideboard", ["price"] = 50, ["label"] = "Шкаф със стойка" },
			[50] = { ["object"] = "v_16_high_bed_mesh_unit", ["price"] = 50, ["label"] = "Шкаф номер загубих бройката" },
			[51] = { ["object"] = "mp_b_str_avunitl_01", ["price"] = 50, ["label"] = "Домашно кино" },
			[52] = { ["object"] = "ch_chint03_hacker", ["price"] = 50, ["label"] = "Хакер сетъп 1" },
			[53] = { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 50, ["label"] = "Офис бюро 1" },
			[54] = { ["object"] = "v_corp_deskseta", ["price"] = 50, ["label"] = "Офис бюро 2" },
			[55] = { ["object"] = "bkr_prop_gunlocker_01a", ["price"] = 50, ["label"] = "Оръжейна" }
		},
	},
	["electronics"] = {
		label = "Електроники",
		items = {
			[1] = { ["object"] = "ba_prop_battle_club_computer_01", ["price"] = 50, ["label"] = "Компютър" },
			[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 50, ["label"] = "Колонка" },
			[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 50, ["label"] = "Колонка 2" },
			[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 50, ["label"] = "Часовник - аларма" },
			[5] = { ["object"] = "v_res_fa_phone", ["price"] = 50, ["label"] = "Домофон" },
			[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 50, ["label"] = "Духалка" },
			[7] = { ["object"] = "v_res_fa_fan", ["price"] = 50, ["label"] = "Вентилатор 2" },
			[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 50, ["label"] = "Екран за прожекции" },
			[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 50, ["label"] = "Монитор" },
			[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 50, ["label"] = "Миксер" },
			[11] = { ["object"] = "prop_cs_cctv", ["price"] = 50, ["label"] = "Охранителна камера" },
			[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 50, ["label"] = "Лаптоп" },
			[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 50, ["label"] = "Монитор 2" },
			[14] = { ["object"] = "prop_speaker_05", ["price"] = 50, ["label"] = "Суб буфер" },
			[15] = { ["object"] = "prop_tv_flat_03b", ["price"] = 50, ["label"] = "Плазма" },
			[16] = { ["object"] = "prop_laptop_01a", ["price"] = 50, ["label"] = "НоЛаптоп" },
			[17] = { ["object"] = "prop_tv_flat_michael", ["price"] = 50, ["label"] = "Плазма 2" },
			[18] = { ["object"] = "prop_dyn_pc", ["price"] = 50, ["label"] = "Компютър от 2001-ва" },
			[19] = { ["object"] = "prop_keyboard_01b", ["price"] = 50, ["label"] = "Клавиатура" },
			[20] = { ["object"] = "prop_mouse_01b", ["price"] = 50, ["label"] = "Мишка" },
			[21] = { ["object"] = "v_ret_gc_phone", ["price"] = 50, ["label"] = "Домашен телефон" },
			[22] = { ["object"] = "prop_tv_flat_01", ["price"] = 50, ["label"] = "Плазма 3" },
			[23] = { ["object"] = "prop_arcade_01", ["price"] = 50, ["label"] = "Аркейд игра" },
			[24] = { ["object"] = "prop_console_01", ["price"] = 50, ["label"] = "Playstation 2" },
			[25] = { ["object"] = "v_res_tre_dvdplayer", ["price"] = 50, ["label"] = "DVD плейъра на баба ти" },
			[26] = { ["object"] = "prop_speaker_08", ["price"] = 50, ["label"] = "Високоговорителчета" },
			[27] = { ["object"] = "prop_cctv_mon_02", ["price"] = 50, ["label"] = "Телевизора на баба ти Елена" },
			[28] = { ["object"] = "prop_tv_flat_02", ["price"] = 50, ["label"] = "Плазма със стойка" },
			[29] = { ["object"] = "prop_cctv_cam_01a", ["price"] = 50, ["label"] = "Охранителна камера 2" },
			[30] = { ["object"] = "prop_dest_cctv_02", ["price"] = 50, ["label"] = "Телевизора на баба ти Елена 2" },
			[31] = { ["object"] = "prop_cctv_cam_07a", ["price"] = 50, ["label"] = "Охранителна камера 3" },
			[32] = { ["object"] = "v_club_vu_deckcase", ["price"] = 50, ["label"] = "DJ пулт 2" },
			[33] = { ["object"] = "v_corp_servercln", ["price"] = 50, ["label"] = "Сървърна машина 2" },
			[34] = { ["object"] = "prop_elecbox_18", ["price"] = 50, ["label"] = "Електронно табло" }
		},
	},
	["lighting"] = {
		label = "Осветителни тела",
		items = {
			[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 50, ["label"] = "Нощна лампа" },
			[2] = { ["object"] = "v_res_desklamp", ["price"] = 50, ["label"] = "Нощна лампа 2" },
			[3] = { ["object"] = "v_res_d_lampa", ["price"] = 50, ["label"] = "Нощна лампа 3" },
			[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 50, ["label"] = "Нощна лампа 4" },
			[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 50, ["label"] = "Нощна лампа 5" },
			[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 50, ["label"] = "Майнкрафт лампа" },
			[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 50, ["label"] = "Лампа 1" },
			[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 50, ["label"] = "Лампа 2" },
			[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 50, ["label"] = "Лампа изгубих бройката" },
			[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 50, ["label"] = "Фикус" },
			[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 50, ["label"] = "Лампа изгубих бройката 2" },
			[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 50, ["label"] = "Висока лампа" },
			[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 50, ["label"] = "Висока лампа 2" },
			[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 50, ["label"] = "Лампа 3" },
			[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 50, ["label"] = "Лампа вентилатор" },
			[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 50, ["label"] = "Висока лампа 3" },
			[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 50, ["label"] = "Лампа за стена" },
			[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 50, ["label"] = "Нощна лампа 6" },
			[19] = { ["object"] = "prop_dummy_light", ["price"] = 50, ["label"] = "Тъпа лампа" },
			[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 50, ["label"] = "Стенна лампа" },
			[21] = { ["object"] = "prop_wall_light_07a", ["price"] = 50, ["label"] = "Стенна лампа 2" },
			[22] = { ["object"] = "prop_wall_light_01a", ["price"] = 50, ["label"] = "Хапче в клетка" },
			[23] = { ["object"] = "v_serv_tu_light2_", ["price"] = 50, ["label"] = "Странна лампа" },
			[24] = { ["object"] = "v_serv_tu_light3_", ["price"] = 50, ["label"] = "Странна лампа 2" },
			[25] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 50, ["label"] = "Лампата не е намерена" },
			[26] = { ["object"] = "v_med_p_floorlamp", ["price"] = 50, ["label"] = "Поредната лампа" },
			[27] = { ["object"] = "v_club_vu_lamp", ["price"] = 50, ["label"] = "Поредната лампа 2" },
			[28] = { ["object"] = "ba_prop_battle_lights_wall_l_a", ["price"] = 50, ["label"] = "Лампата не е намерена 2" },
			[29] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 50, ["label"] = "Лампа 404" },
			[30] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 50, ["label"] = "Лампа 404 2" },
			[31] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 50, ["label"] = "Лампа 404 3" },
			[32] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 50, ["label"] = "Лампа 404 4" },
			[33] = { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 50, ["label"] = "Лампата е намерена" },
			[34] = { ["object"] = "prop_oldlight_01b", ["price"] = 50, ["label"] = "Странна лампа 3" },
			[35] = { ["object"] = "v_ind_cflight02", ["price"] = 50, ["label"] = "Поредната лампа 3 " },
			[36] = { ["object"] = "v_ind_cflight", ["price"] = 50, ["label"] = "Поредната лампа 4" },
			[37] = { ["object"] = "xm_prop_base_wall_lampa", ["price"] = 50, ["label"] = "Прожектор 1" },
			[38] = { ["object"] = "xm_prop_base_wall_lampb", ["price"] = 50, ["label"] = "Прожектор 2" },
			[39] = { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 50, ["label"] = "Поредната лампа 5" }
		},
	},
	["tables"] = {
		label = "Маси",
		items = {
			[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 50, ["label"] = "Масичка 1" },
			[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 50, ["label"] = "Кръгла масичка" },
			[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 50, ["label"] = "Висока масичка" },
			[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 50, ["label"] = "Масичка 2" },
			[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 50, ["label"] = "Масичка 3" },
			[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 50, ["label"] = "Масичка 4" },
			[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 50, ["label"] = "Масичка 5" },
			[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 50, ["label"] = "Масичка 6" },
			[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 50, ["label"] = "Масичка 7" },
			[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 50, ["label"] = "Нощно шкафче 4" },
			[11] = { ["object"] = "v_res_mddesk", ["price"] = 50, ["label"] = "Бюро" }, 
			[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 50, ["label"] = "Масичка 8" },
			[13] = { ["object"] = "v_res_m_console", ["price"] = 50, ["label"] = "Масичка 9" },
			[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 50, ["label"] = "Масичка 10" },
			[15] = { ["object"] = "v_res_m_h_console", ["price"] = 50, ["label"] = "Бюро 2" },
			[16] = { ["object"] = "v_res_m_stool", ["price"] = 50, ["label"] = "Масичка 11" },
			[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 50, ["label"] = "Шкафче загубих бройката" },
			[18] = { ["object"] = "v_res_tre_table2", ["price"] = 50, ["label"] = "Маса" },
			[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 50, ["label"] = "Стойка за телевизор" },
			[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 50, ["label"] = "Стойка за телевизор 2" },
			[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 50, ["label"] = "Маса за кафе" },
			[22] = { ["object"] = "v_med_p_desk", ["price"] = 50, ["label"] = "Бюро 3" },
			[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 50, ["label"] = "Малка масичка 1" },
			[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 50, ["label"] = "Малка масичка 2" },
			[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 50, ["label"] = "Малка масичка 3" },
			[26] = { ["object"] = "v_ret_csr_table", ["price"] = 50, ["label"] = "Голяма кръгла маса" },
			[27] = { ["object"] = "v_res_mconsoletrad", ["price"] = 50, ["label"] = "Висока маса" },
			[28] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 50, ["label"] = "Конферентна маса" },
			[29] = { ["object"] = "v_ret_tablesml", ["price"] = 50, ["label"] = "Висока маса 2" },
			[30] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 50, ["label"] = "Масичка за кафе 1" },
			[31] = { ["object"] = "apa_mp_h_yacht_side_table_01", ["price"] = 50, ["label"] = "Масичка за кафе 2" },
			[32] = { ["object"] = "apa_mp_h_yacht_side_table_02", ["price"] = 50, ["label"] = "Масичка за кафе 3" },
			[33] = { ["object"] = "apa_mp_h_tab_sidelrg_04", ["price"] = 50, ["label"] = "Масичка за кафе 4" },
			[34] = { ["object"] = "v_club_vu_table", ["price"] = 50, ["label"] = "Маса с покривка" },
			[35] = { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 50, ["label"] = "Стъклена маса 1" },
			[36] = { ["object"] = "bkr_prop_weed_table_01b", ["price"] = 50, ["label"] = "Сгъваема маса" },
			[37] = { ["object"] = "ba_prop_int_trad_table", ["price"] = 50, ["label"] = "Масичка за кафе 5" },
			[38] = { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 50, ["label"] = "Стъклена маса 2" },
			[39] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 50, ["label"] = "Масичка за кафе 6" },
			[40] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 50, ["label"] = "Стъклена маса 3" },
			[41] = { ["object"] = "bkr_prop_coke_table01a", ["price"] = 50, ["label"] = "Маса с кока" },
			[42] = { ["object"] = "gr_prop_gr_bench_03b", ["price"] = 50, ["label"] = "Стенна маса с оръжия 1" },
			[43] = { ["object"] = "gr_prop_gr_bench_04b", ["price"] = 50, ["label"] = "Стенна маса с оръжия 2" },
			[44] = { ["object"] = "gr_prop_gr_bench_01b", ["price"] = 50, ["label"] = "Стенна маса с оръжия 3" },
		},
	},
	["plants"] = {
		label = "Растения",
		items = {
			[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 50, ["label"] = "Растение 1" },
			[2] = { ["object"] = "v_corp_bombplant", ["price"] = 50, ["label"] = "Растение 2" },		
			[3] = { ["object"] = "v_res_mflowers", ["price"] = 50, ["label"] = "Ваза с цветя 1" },	
			[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 50, ["label"] = "Китайско растение" },	
			[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 50, ["label"] = "Бананово растение" },	
			[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 50, ["label"] = "Палмово дърво 1" },	
			[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 50, ["label"] = "Палмово дърво 2" },	
			[8] = { ["object"] = "v_res_m_urn", ["price"] = 50, ["label"] = "Растение в урна" },	
			[9] = { ["object"] = "v_res_rubberplant", ["price"] = 50, ["label"] = "Растение 3" },	
			[10] = { ["object"] = "v_res_tre_plant", ["price"] = 50, ["label"] = "Растение 4" },	
			[11] = { ["object"] = "v_res_tre_tree", ["price"] = 50, ["label"] = "Растение 5" },	
			[12] = { ["object"] = "v_med_p_planter", ["price"] = 50, ["label"] = "Растение 6" },	
			[13] = { ["object"] = "v_ret_flowers", ["price"] = 50, ["label"] = "Ваза с цветя 2" },
			[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 50, ["label"] = "Ваза с цветя 3" },
			[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 50, ["label"] = "Ваза с цветя 4" },	
			[16] = { ["object"] = "v_res_m_vasefresh", ["price"] = 50, ["label"] = "Ваза с цветя 5" },
			[17] = { ["object"] = "v_res_rosevasedead", ["price"] = 50, ["label"] = "Ваза с мъртви рози" },
			[18] = { ["object"] = "v_res_exoticvase", ["price"] = 50, ["label"] = "Ваза с цветя 6" },
			[19] = { ["object"] = "v_res_rosevase", ["price"] = 50, ["label"] = "Ваза с рози" },
			[20] = { ["object"] = "prop_pot_plant_6a", ["price"] = 50, ["label"] = "Висящо растение" },
			[21] = { ["object"] = "prop_pot_plant_02a", ["price"] = 50, ["label"] = "Саксия с растение" },
			[22] = { ["object"] = "v_res_fh_flowersa", ["price"] = 50, ["label"] = "Ваза с цвете" },
		},
	},
	["kitchen"] = {
		label = "Кухня",
		items = {
			[1] = { ["object"] = "prop_washer_01", ["price"] = 50, ["label"] = "Прахосмукачка 1" },
			[2] = { ["object"] = "prop_washer_02", ["price"] = 50, ["label"] = "Прахосмукачка 2" },
			[3] = { ["object"] = "prop_washer_03", ["price"] = 50, ["label"] = "Прахосмукачка 3" },
			[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 50, ["label"] = "Панер за пране" },
			[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 50, ["label"] = "Хладилник 1" },
			[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 50, ["label"] = "Хладилник 2" },
			[7] = { ["object"] = "prop_fridge_01", ["price"] = 50, ["label"] = "Хладилник 3" },
			[8] = { ["object"] = "prop_fridge_03", ["price"] = 50, ["label"] = "Хладилник 4" },
			[9] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 50, ["label"] = "Хладилник 5" },
			[10] = { ["object"] = "prop_trailr_fridge", ["price"] = 50, ["label"] = "Хладилник 6" },
			[11] = { ["object"] = "prop_cooker_03", ["price"] = 50, ["label"] = "Печка 1" },
			[12] = { ["object"] = "v_res_ovenhobmod", ["price"] = 50, ["label"] = "Печка 2" },
			[13] = { ["object"] = "prop_micro_01", ["price"] = 50, ["label"] = "Микровълнова 1" },
			[14] = { ["object"] = "prop_micro_02", ["price"] = 50, ["label"] = "Микровълнова 2" },
			[15] = { ["object"] = "prop_wok", ["price"] = 50, ["label"] = "Тиган" },
			[16] = { ["object"] = "v_res_cakedome", ["price"] = 50, ["label"] = "Поднос с кексчета" },
			[17] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 50, ["label"] = "Дъска за рязане" },
			[18] = { ["object"] = "v_res_mutensils", ["price"] = 50, ["label"] = "Прибори за кухня" },
			[19] = { ["object"] = "v_res_pestle", ["price"] = 50, ["label"] = "Хаванче" },
			[20] = { ["object"] = "v_ret_ta_paproll", ["price"] = 50, ["label"] = "Домакинско руло 1" },
			[21] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 50, ["label"] = "Домакинско руло 2" },
			[22] = { ["object"] = "v_ret_fh_pot01", ["price"] = 50, ["label"] = "Тенджера 1" },
			[23] = { ["object"] = "v_ret_fh_pot02", ["price"] = 50, ["label"] = "Тенджера 2" },
			[24] = { ["object"] = "v_ret_fh_pot05", ["price"] = 50, ["label"] = "Тенджера 3" },
			[25] = { ["object"] = "prop_pot_03", ["price"] = 50, ["label"] = "Тенджера 4" },
			[26] = { ["object"] = "prop_pot_04", ["price"] = 50, ["label"] = "Тенджера 5" },
			[27] = { ["object"] = "prop_pot_05", ["price"] = 50, ["label"] = "Тенджера 6" },
			[28] = { ["object"] = "prop_pot_06", ["price"] = 50, ["label"] = "Тенджера 7" },
			[29] = { ["object"] = "prop_pot_rack", ["price"] = 50, ["label"] = "Закачени тенджери" },
			[30] = { ["object"] = "prop_kitch_juicer", ["price"] = 50, ["label"] = "Миксер" },
			[31] = { ["object"] = "v_res_mkniferack", ["price"] = 50, ["label"] = "Закачени ножове" },
			[32] = { ["object"] = "v_res_mchopboard", ["price"] = 50, ["label"] = "Дъска за рязане 2" },
			[33] = { ["object"] = "prop_cs_kettle_01", ["price"] = 50, ["label"] = "Чайник" }
		},
	},
	["bathroom"] = {
		label = "Тоалетна",
		items = {
			[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 50, ["label"] = "Тоалетна 1" },
			[2] = { ["object"] = "prop_toilet_01", ["price"] = 50, ["label"] = "Тоалетна 2" },
			[3] = { ["object"] = "prop_toilet_02", ["price"] = 50, ["label"] = "Тоалетна 3" },
			[4] = { ["object"] = "prop_sink_02", ["price"] = 50, ["label"] = "Мивка 1" },
			[5] = { ["object"] = "prop_sink_04", ["price"] = 50, ["label"] = "Мивка 2" },
			[6] = { ["object"] = "prop_sink_05", ["price"] = 50, ["label"] = "Мивка 3" },
			[7] = { ["object"] = "prop_sink_06", ["price"] = 50, ["label"] = "Мивка 4" },
			[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 50, ["label"] = "Сапунерка" },
			[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 50, ["label"] = "Решетка за душ" },
			[10] = { ["object"] = "prop_handdry_01", ["price"] = 50, ["label"] = "Сушилня за ръце 1" },
			[11] = { ["object"] = "prop_handdry_02", ["price"] = 50, ["label"] = "Сушилня за ръце 2" },
			[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 50, ["label"] = "Поставка за кърпи 1" },
			[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 50, ["label"] = "Поставка за кърпи 2" },
			[14] = { ["object"] = "prop_towel_01", ["price"] = 50, ["label"] = "Хавлиена кърпа 1" },
			[15] = { ["object"] = "v_res_mbtowel", ["price"] = 50, ["label"] = "Хавлиена кърпа 2" },
			[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 50, ["label"] = "Хавлиена кърпа 3" },
			[17] = { ["object"] = "v_ilev_mm_faucet", ["price"] = 50, ["label"] = "Кранче" },
			[18] = { ["object"] = "v_res_tre_washbasket", ["price"] = 50, ["label"] = "Панер за пране 2" },
			[19] = { ["object"] = "prop_toilet_soap_02", ["price"] = 50, ["label"] = "Сапун" },
			[20] = { ["object"] = "prop_bar_sink_01", ["price"] = 50, ["label"] = "Мивка 5" },
			[21] = { ["object"] = "v_res_mbath", ["price"] = 50, ["label"] = "Вана 1" },
			[22] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 50, ["label"] = "Вана 2" }
		}
	},
	["medical"] = {
		label = "Болнични",
		items = {
			[1] = { ["object"] = "v_med_barrel", ["price"] = 50, ["label"] = "Варел" },
			[2] = { ["object"] = "v_med_apecrate", ["price"] = 50, ["label"] = "Медицинска клетка" },
			[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 50, ["label"] = "Медицински клетки" },
			[4] = { ["object"] = "v_med_bed1", ["price"] = 50, ["label"] = "Медицинско легло 1" },
			[5] = { ["object"] = "v_med_bed2", ["price"] = 50, ["label"] = "Медицинско легло 2" },
			[6] = { ["object"] = "v_med_bedtable", ["price"] = 50, ["label"] = "Медицинска масичка" },
			[7] = { ["object"] = "v_med_bench1", ["price"] = 50, ["label"] = "Медицинско бюро 1" },
			[8] = { ["object"] = "v_med_bench2", ["price"] = 50, ["label"] = "Медицинско бюро 2" },
			[9] = { ["object"] = "v_med_benchcentr", ["price"] = 50, ["label"] = "Медицинско бюро 3" },
			[10] = { ["object"] = "v_med_benchset1", ["price"] = 50, ["label"] = "Медицински сет за бюро" },
			[11] = { ["object"] = "v_med_bigtable", ["price"] = 50, ["label"] = "Медицинска маса" },
			[12] = { ["object"] = "v_med_bin", ["price"] = 50, ["label"] = "Медицинско кошче 1" },
			[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 50, ["label"] = "Центрофуга" },
			[14] = { ["object"] = "v_med_cooler", ["price"] = 50, ["label"] = "Охладител" },
			[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 50, ["label"] = "Монитор висящ от тавана" },
			[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 50, ["label"] = "Маса за аутопсия" },
			[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 50, ["label"] = "Медицинско кошче 2" },
			[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 50, ["label"] = "Медицинска количка" },
			[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 50, ["label"] = "Токсичен химикал" },
			[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 50, ["label"] = "Медицинска мафа 2" },
			[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 50, ["label"] = "Кутия с файлове" },
			[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 50, ["label"] = "Чекмеджета с файлове" },
			[23] = { ["object"] = "v_med_cor_hose", ["price"] = 50, ["label"] = "Маркуч" },
			[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 50, ["label"] = "Високи шкафчета" },
			[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 50, ["label"] = "Светлинна кутия" },
			[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 50, ["label"] = "Медицинско столче" },
			[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 50, ["label"] = "Мини хладилник" },
			[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 50, ["label"] = "Хартиени кърпи" },
			[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 50, ["label"] = "Фотокопир" },
			[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 50, ["label"] = "Телевизод на стойка" },
			[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 50, ["label"] = "Стенен медицински шкаф" },
			[32] = { ["object"] = "v_med_examlight", ["price"] = 50, ["label"] = "Лампа за операционна" },
			[33] = { ["object"] = "v_med_gastank", ["price"] = 50, ["label"] = "Резервоар с газ" },
			[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 50, ["label"] = "Хазмат скенер" },
			[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 50, ["label"] = "Медицински уреди на стена ддз" },
			[36] = { ["object"] = "v_med_hospseating1", ["price"] = 50, ["label"] = "Болнични седалки" },
			[37] = { ["object"] = "v_med_hosptable", ["price"] = 50, ["label"] = "Болнична маса" },
			[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["label"] = "Кутия с ръкавици от латекс" },
			[39] = { ["object"] = "v_med_medwastebin", ["price"] = 50, ["label"] = "Кошче за токсични отпадъци" },
			[40] = { ["object"] = "v_med_oscillator3", ["price"] = 50, ["label"] = "Осцилатор" },
			[41] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 50, ["label"] = "Чекмеджета на колелца 1" },
			[42] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 50, ["label"] = "Масичка на колелца" },
			[43] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 50, ["label"] = "Комплект за първа помощ" },
			[44] = { ["object"] = "prop_bonesaw", ["price"] = 50, ["label"] = "Костен трион" },
			[45] = { ["object"] = "prop_ld_health_pack", ["price"] = 50, ["label"] = "Аптечка" }
		},
	},
	["walldecoration"] = {
		label = "Арт",
		items = {
			[1] = { ["object"] = "apa_p_h_acc_artwalll_02", ["price"] = 50, ["label"] = "Арт стена 1" },
			[2] = { ["object"] = "v_ind_cs_toolboard", ["price"] = 50, ["label"] = "Gereedschap" },
			[3] = { ["object"] = "ex_office_swag_paintings03", ["price"] = 50, ["label"] = "Картини" },
			[4] = { ["object"] = "ex_mp_h_acc_artwallm_03", ["price"] = 50, ["label"] = "Арт стена 2" },
			[5] = { ["object"] = "ex_p_h_acc_artwallm_04", ["price"] = 50, ["label"] = "Арт стена 3" },
			[6] = { ["object"] = "ex_p_h_acc_artwalll_01", ["price"] = 50, ["label"] = "Арт стена 4" },
			[7] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 50, ["label"] = "Арт стена 5" },
			[8] = { ["object"] = "ex_mp_h_acc_artwallm_02", ["price"] = 50, ["label"] = "Арт стена 6" },
			[9] = { ["object"] = "ex_p_h_acc_artwallm_03", ["price"] = 50, ["label"] = "Арт стена 7" },
			[10] = { ["object"] = "apa_mp_h_acc_artwallm_02", ["price"] = 50, ["label"] = "Арт стена 8" },
			[11] = { ["object"] = "apa_mp_h_acc_artwalll_02", ["price"] = 50, ["label"] = "Арт стена 9" },
			[12] = { ["object"] = "apa_mp_h_acc_artwallm_04", ["price"] = 50, ["label"] = "Арт стена 10" },
			[13] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 50, ["label"] = "Дъска за дартс 1" },
			[14] = { ["object"] = "prop_dart_bd_01", ["price"] = 50, ["label"] = "Дъска за дартс 2" }
		},
	},
}