Config = {}
Config.MaxWidth = 5.0
Config.MaxHeight = 5.0
Config.MaxLength = 5.0
Config.DamageNeeded = 100.0
Config.IdleCamera = true
Config.EnableProne = true
Config.JointEffectTime = 60
Config.RemoveWeaponDrops = true
Config.RemoveWeaponDropsTimer = 25
Config.DefaultPrice = 20 -- carwash
Config.DirtLevel = 0.1 --carwash dirt level

Config.Blips = {
    {name = "Полицейско Управление", spriteid = 60, color = 38, scale = 0.55, coords = vector3(381.05792236328, -1593.2142333984, 30.04877281189)},
    {name = "Police Sandy Shores", spriteid = 60, color = 38, scale = 0.55, coords = vector3(1854.047, 3685.172, 34.26703)},
    {name = "Park Ranger", spriteid = 60, color = 38, scale = 0.55, coords = vector3(381.48672, 796.07403, 190.4904)},
    {name = "Police La Mesa", spriteid = 60, color = 38, scale = 0.55, coords = vector3(842.81182, -1296.276, 28.244918)},
    {name = 'Paleto Sheriff', spriteid = 60, color = 52, scale = 0.55, coords = vector3(-437.66513061523, 6013.8178710938, 32.271339416504)},
    {name = "Болница", spriteid = 61, color = 49, scale = 0.55, coords = vector3(354.26, -1401.06, 32.5)},
    {name = "Diamond Casino & Resort", spriteid = 680, color = 27, scale = 0.65, coords = vector3(929.81, 44.04, 81.1)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(150.3254, -1039.767, 29.36798)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(314.4396, -277.7154, 54.16474)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(-1213.453, -329.8271, 37.78094)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(-2963.802, 483.0118, 15.69698)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(-109.326, 6464.429, 31.62672)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(-350.5362, -48.27618, 49.04624)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(1175.0191, 2708.2636, 38.087909)},
    {name = 'Банка', spriteid = 276, color = 11, scale = 0.6, coords = vector3(236.37, 217.25, 106.28)},
    {name = 'Железария', spriteid = 566, color = 0, scale = 0.48, coords = vector3(-11.79454, 6499.9726, 31.498649)},
    {name = 'Железария', spriteid = 566, color = 0, scale = 0.48, coords = vector3(44.74, -1748.21, 29.52)},
    {name = 'Железария', spriteid = 566, color = 0, scale = 0.48, coords = vector3(2748.84, 3472.50, 55.67)},
    {name = 'Гараж-Legion', spriteid = 357, color = 3, scale = 0.48, coords = vector3(215.412, -805.607, 30.804)},
    {name = 'Гараж-Pillbox', spriteid = 357, color = 3, scale = 0.48, coords = vector3(278.581, -345.742, 44.919)},
    {name = 'Гараж-RED', spriteid = 357, color = 3, scale = 0.48, coords = vector3(-330.159, -780.161, 33.964)},
    {name = 'Гараж-Vespucci', spriteid = 357, color = 3, scale = 0.48, coords = vector3(-1159.089, -740.023, 19.889)},
    {name = 'Гараж-Paletto', spriteid = 357, color = 3, scale = 0.48, coords = vector3(82.576, 6421.771, 31.681)},
    {name = 'Гараж-Sandy', spriteid = 357, color = 3, scale = 0.48, coords = vector3(1714.6087, 3768.1892, 34.305503)},
    {name = 'Гараж-Crastenburg', spriteid = 357, color = 3, scale = 0.48, coords = vector3(-1283.297, -212.8643, 32.32)},
    {name = 'Оръжеен магазин', spriteid = 110, color = 26, scale = 0.43, coords = vector3(20.69, -1108.116, 29.79)},
    {name = 'Pitstop', spriteid = 84, color = 1, scale = 0.8, coords = vector3(914.92, -1559.53, 30.74)},
    -- {name = 'RaceMonkeyService', spriteid = 596, color = 38, scale = 0.7, coords = vector3(-1417.6279296875, -446.66510009766, 35.90970993042)}, 
    -- {name = 'Taxi', spriteid = 198, color = 5, scale = 0.55, coords = vector3(-1607.483, -843.1992, 10.09945)},  
    {name = 'Община', spriteid = 590, color = 0, scale = 0.43, coords = vector3(-550.3251, -195.0801, 38.226909)},
    {name = 'Сервиз', spriteid = 72, color = 0, scale = 0.5, coords = vector3(-682.01, -773.58, 33.01)}, -- vector3(-682.01, -773.58, 33.01)
    {name = 'Auto Deluxe', spriteid = 289, color = 0, scale = 0.4, coords = vector3(535.01434, -178.8619, 54.402854)},
    {name = 'Автомивка', spriteid = 100, color = 0, scale = 0.53, coords = vector3(47.71, -1391.89, 29.56)},
    {name = 'Технически прегледи', spriteid = 79, color = 21, scale = 0.7, coords = vector3(-360.0502, -133.7123, 38.680244)},
    {name = 'Бижутерия', spriteid = 617, color = 26, scale = 0.43, coords = vector3(-624.6099, -232.6981, 38.05706)},
    {name = 'Депо', spriteid = 67, color = 44, scale = 0.43, coords = vector3(403.28237915039, -1636.791015625, 28.618518829346)},
    {name = 'Затвор', spriteid = 253, color = 0, scale = 0.43, coords = vector3(1680.23,  2559.30, 45.56)},
    --{name = 'Рециклиране', spriteid = 467, color = 69, scale = 0.43, coords = vector3(91.03852, -1603.531, 31.079059)},
    {name = 'Дилър МПС', spriteid = 523, color = 3, scale = 0.43, coords = vector3(-46.09263, -1096.941, 26.422355)},
    {name = 'Vanilla Unicorn', spriteid = 121, color = 27, scale = 0.43, coords = vector3(127.82, -1296.91, 29.56)},
    {name = 'Burgershot', spriteid = 106, color = 1, scale = 0.43, coords = vector3(-1190.757, -889.0961, 13.98)},
    {name = 'Cranberry', spriteid = 93, color = 3, scale = 0.7, coords = vector3(-1077.339, -314.4102, 37.807868)},
    -- {name = 'Red Circle', spriteid = 590, color = 1, scale = 0.7, coords = vector3(-310.1506, 221.63328, 87.928329)},
    -- {name = 'Planet', spriteid = 590, color = 3, scale = 0.7, coords = vector3(-1603.418, -1884.111, 16.255737)},
    -- {name = 'Bakery', spriteid = 106, color = 3, scale = 0.7, coords = vector3(142.13729, -1463.927, 29.357074)},
    {name = 'Наем на лодки', spriteid = 410, color = 42, scale = 0.65, coords = vector3(-753.55, -1512.24, 5.02)},
    {name = 'Наем на коли', spriteid = 227, color = 32, scale = 0.65, coords = vector3(109.97, -1088.61, 28.30)},
    {name = 'Crastenburg Hotel', spriteid = 475, color = 26, scale = 0.65, coords = vector3(-1203.04, -203.65, 39.32)},
    {name = 'Fraud Center', spriteid = 88, color = 59, scale = 0.65, coords = vector3(809.03039, -812.9302, 26.184795)},
    {name = 'Flight School', spriteid = 90, color = 40, scale = 0.65, coords = vector3(-1645.065, -3142.812, 13.992218)},
    {name = 'Център за рециклиране', spriteid = 365, color = 2, scale = 0.65, coords = vector3(744.68, -1401.77, 26.55)},
}

Config.Teleports = {
    ['JudgeEnter'] = {
        enter = true,
        coords = vector3(-1379.59, -499.38, 33.16),
        l = 1.6,
        h = 2.2,
        heading = 9,
        minZ = 31.96,
        maxZ = 35.36,
        teleportCoords = vector3(-1399.00, -480.234, 72.04),
        teleportHeading = 270.81372070313
    },
    ['JudgeExit'] = {
        enter = false,
        coords = vector3(-1399.29, -480.38, 72.04),
        l = 2.4,
        h = 2.6,
        heading = 7,
        minZ = 71.04,
        maxZ = 73.64,
        teleportCoords = vector3(-1379.49, -499.99, 33.1574),
        teleportHeading = 186.30
    },
    ['ZenEnter'] = {
        enter = true,
        coords = vector3(-66.79, -802.4, 44.23),
        l = 2.4,
        h = 2.4,
        heading = 340,
        minZ = 42.0,
        maxZ = 46.0,
        teleportCoords = vector3(-78.54, -832.17, 243.39),
        teleportHeading = 340.0
    },
    ['ZenExit'] = {
        enter = false,
        coords = vector3(-78.54, -832.17, 243.39),
        l = 2.6,
        h = 2.6,
        heading = 340,
        minZ = 241.04,
        maxZ = 245.64,
        teleportCoords = vector3(-66.79, -802.4, 44.23),
        teleportHeading = 340.0
    }
}

Config.BlacklistedScenarios = {
    ['TYPES'] = {
        "WORLD_VEHICLE_MILITARY_PLANES_SMALL",
        "WORLD_VEHICLE_MILITARY_PLANES_BIG",
        "WORLD_VEHICLE_AMBULANCE",
        "WORLD_VEHICLE_POLICE_NEXT_TO_CAR",
        "WORLD_VEHICLE_POLICE_CAR",
        "WORLD_VEHICLE_POLICE_BIKE",
    },
    ['GROUPS'] = {
        2017590552,
        2141866469,
        1409640232,
        `ng_planes`,
    }
}

Config.BlacklistedVehs = {
    [`SHAMAL`] = true,
    [`LUXOR`] = true,
    [`LUXOR2`] = true,
    [`JET`] = true,
    [`LAZER`] = true,
    [`BUZZARD`] = true,
    [`BUZZARD2`] = true,
    [`ANNIHILATOR`] = true,
    [`SAVAGE`] = true,
    [`TITAN`] = true,
    [`RHINO`] = true,
    [`FIRETRUK`] = true,
    [`MULE`] = true,
    [`MAVERICK`] = true,
    [`BLIMP`] = true,
    [`AIRTUG`] = true,
    [`HYDRA`] = true,
    [`OPPRESSOR`] = true,
    [`technical3`] = true,
    [`insurgent3`] = true,
    [`apc`] = true,
    [`tampa3`] = true,
    [`trailersmall2`] = true,
    [`halftrack`] = true,
    [`hunter`] = true,
    [`vigilante`] = true,
    [`akula`] = true,
    [`barrage`] = true,
    [`khanjali`] = true,
    [`caracara`] = true,
    [`blimp3`] = true,
    [`menacer`] = true,
    [`oppressor2`] = true,
    [`scramjet`] = true,
    [`strikeforce`] = true,
    [`cerberus`] = true,
    [`cerberus2`] = true,
    [`cerberus3`] = true,
    [`scarab`] = true,
    [`scarab2`] = true,
    [`scarab3`] = true,
    [`rrocket`] = true,
    [`ruiner2`] = true,
    [`deluxo`] = true,
    [`policeb`] = true,
    [`besra`] = true,
    [`ambulance`] = true,
}

Config.BlacklistedPeds = {
    [`s_m_y_ranger_01`] = true,
    [`s_m_y_sheriff_01`] = true,
    [`s_m_y_cop_01`] = true,
    [`s_f_y_sheriff_01`] = true,
    [`s_f_y_cop_01`] = true,
    [`s_m_y_hwaycop_01`] = true,
}

Config.CarWash = { -- carwash
    [1] = {
        ["label"] = "Hands Free Carwash",
        ["coords"] = vector3(25.29, -1391.96, 29.33),
    },
    [2] = {
        ["label"] = "Hands Free Carwash",
        ["coords"] = vector3(174.18, -1736.66, 29.35),
    },
    [3] = {
        ["label"] = "Hands Free Carwash",
        ["coords"] = vector3(-74.56, 6427.87, 31.44),
    },
    [5] = {
        ["label"] = "Hands Free Carwash",
        ["coords"] = vector3(1363.22, 3592.7, 34.92),
    },
    [6] = {
        ["label"] = "Hands Free Carwash",
        ["coords"] = vector3(-699.62, -932.7, 19.01),
    }
}

Config.Healing = 3 -- // If this is 0, then its disabled.. Default: 3.. That means, if a person lies in a bed, then he will get 1 health every 3 seconds.

Config.objects = {
	SitAnimation = {anim='PROP_HUMAN_SEAT_CHAIR_MP_PLAYER'},
	BedBackAnimation = {dict='anim@gangops@morgue@table@', anim='ko_front'},
	BedStomachAnimation = {anim='WORLD_HUMAN_SUNBATHE'},
	BedSitAnimation = {anim='WORLD_HUMAN_PICNIC'},
	locations = {
		[1631638868] = {object="v_med_bed1", verticalOffsetX=-0.05, verticalOffsetY=-0.2, verticalOffsetZ=-1.3, direction=0.0},
		[2117668672] = {object="v_med_bed2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0}
	}
}

Config.PropList = {
    -- Casual Props
    ['weapon_katanas'] = {
        ['name'] = 'weapon_katanas',
        ['prop'] = 'katana_sheath',
        ['hash'] = GetHashKey('katana_sheath'),
        ['bone-index'] = {
            ['bone'] = 24817,
            ['X'] = 0.07,
            ['Y'] = -0.15,
            ['Z'] = 0.02,
            ['XR'] = 225.0,
            ['YR'] = 8.0,
            ['ZR'] = 90.0,
        },
    },
    ['vodka'] = {
        ['name'] = 'vodka',
        ['prop'] = 'ba_prop_battle_shot_glass_01',
        ['hash'] = GetHashKey('ba_prop_battle_shot_glass_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.01,
            ['Z'] = -0.01,
            ['XR'] = 0.0,
            ['YR'] = 0.00,
            ['ZR'] = 0.0,
        },
    },
    ['champ'] = {
        ['name'] = 'champ',
        ['prop'] = 'prop_drink_champ',
        ['hash'] = GetHashKey('prop_drink_champ'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.10,
            ['Y'] = -0.03,
            ['Z'] = 0.03,
            ['XR'] = -100.0,
            ['YR'] = 0.00,
            ['ZR'] = -10.0,
        },
    },
    ['redwine'] = {
        ['name'] = 'redwine',
        ['prop'] = 'prop_drink_redwine',
        ['hash'] = GetHashKey('prop_drink_redwine'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.10,
            ['Y'] = -0.03,
            ['Z'] = 0.03,
            ['XR'] = -100.0,
            ['YR'] = 0.00,
            ['ZR'] = -10.0,
        },
    },
    ['cocktail'] = {
        ['name'] = 'Cocktail',
        ['prop'] = 'prop_tequila',
        ['hash'] = GetHashKey('prop_tequila'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.10,
            ['Y'] = -0.03,
            ['Z'] = 0.03,
            ['XR'] = -100.0,
            ['YR'] = 0.00,
            ['ZR'] = -10.0,
        },
    },
    ['cocktail2'] = {
        ['name'] = 'Cocktail',
        ['prop'] = 'prop_tequsunrise',
        ['hash'] = GetHashKey('prop_tequsunrise'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.01,
            ['Z'] = -0.06,
            ['XR'] = 0.0,
            ['YR'] = 0.00,
            ['ZR'] = 0.0,
        },
    },
    ['cocktail3'] = {
        ['name'] = 'Cocktail',
        ['prop'] = 'prop_cocktail',
        ['hash'] = GetHashKey('prop_cocktail'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.10,
            ['Y'] = -0.03,
            ['Z'] = 0.03,
            ['XR'] = -100.0,
            ['YR'] = 0.00,
            ['ZR'] = -10.0,
        },
    },
    
    ['whtwine'] = {
        ['name'] = 'Whtwine',
        ['prop'] = 'prop_drink_whtwine',
        ['hash'] = GetHashKey('prop_drink_whtwine'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.10,
            ['Y'] = -0.03,
            ['Z'] = 0.03,
            ['XR'] = -100.0,
            ['YR'] = 0.00,
            ['ZR'] = -10.0,
        },
    },
    ['beer'] = {
        ['name'] = 'Beer',
        ['prop'] = 'prop_amb_beer_bottle',
        ['hash'] = GetHashKey('prop_amb_beer_bottle'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.00,
            ['ZR'] = 0.0,
        },
    },
    ['whiskey'] = {
        ['name'] = 'Whiskey',
        ['prop'] = 'prop_drink_whisky',
        ['hash'] = GetHashKey('prop_drink_whisky'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.01,
            ['Z'] = -0.06,
            ['XR'] = 0.0,
            ['YR'] = 0.00,
            ['ZR'] = 0.0,
        },
    },
    ['PS5'] = {
        ['name'] = 'PS5',
        ['prop'] = 'ex_office_swag_electronic',
        ['hash'] = GetHashKey('ex_office_swag_electronic'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = -0.05,
            ['Y'] = 0.00,
            ['Z'] = 0.0,
            ['XR'] = -30.0,
            ['YR'] = -120.00,
            ['ZR'] = 30.00,
        },
    },
    ['eggplant'] = {
        ['name'] = 'Eggplant',
        ['prop'] = 'luno_eggplant',
        ['hash'] = GetHashKey('luno_eggplant'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.01,
            ['XR'] = -25.0,
            ['YR'] = -16.0,
            ['ZR'] = -120.0,
        },
    },
    ['pizza'] = {
        ['name'] = 'Pizza',
        ['prop'] = 'v_res_tt_pizzaplate',
        ['hash'] = GetHashKey('v_res_tt_pizzaplate'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.20,
            ['Y'] = 0.038,
            ['Z'] = 0.051,
            ['XR'] = 15.0,
            ['YR'] = 155.0,
            ['ZR'] = 0.0,
        },
    },
    ['bowl'] = {
        ['name'] = 'Bowl',
        ['prop'] = 'prop_cs_bowl_01',
        ['hash'] = GetHashKey('prop_cs_bowl_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.050,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['cucumber'] = {
        ['name'] = 'Cucumber',
        ['prop'] = 'luno_cucumber',
        ['hash'] = GetHashKey('luno_cucumber'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.12,
            ['Y'] = 0.05,
            ['Z'] = 0.02,
            ['XR'] = 20.0,
            ['YR'] = -90.0,
            ['ZR'] = 110.0,
        },
    },
    ['kukuruz'] = {
        ['name'] = 'Kukuruz',
        ['prop'] = 'luno_corn',
        ['hash'] = GetHashKey('luno_corn'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.01,
            ['XR'] = 115.0,
            ['YR'] = -86.0,
            ['ZR'] = 180.0,
        },
    },
    ['Spatula'] = {
        ['name'] = 'Spatula',
        ['prop'] = 'prop_fish_slice_01',
        ['hash'] = GetHashKey('prop_fish_slice_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.08,
            ['Y'] = 0.0,
            ['Z'] = -0.02,
            ['XR'] = 0.0,
            ['YR'] = -25.0,
            ['ZR'] = 130.0,
        },
    },
    ['Stone'] = {
        ['name'] = 'Stone',
        ['prop'] = 'rock_4_cl_2_1',
        ['hash'] = GetHashKey('rock_4_cl_2_1'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.2,
            ['Y'] = 0.1,
            ['Z'] = -0.3,
            ['XR'] = 170.0,
            ['YR'] = 100.0,
            ['ZR'] = 180.0,
        },
    },
    ['Fork'] = {
        ['name'] = 'Fork',
        ['prop'] = 'prop_cs_fork',
        ['hash'] = GetHashKey('prop_cs_fork'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = -0.005,
            ['Y'] = 0.00,
            ['Z'] = 0.00,
            ['XR'] = 175.0,
            ['YR'] = 160.0,
            ['ZR'] = 0.0,
        },
    },
    ['Axe'] = {
        ['name'] = 'Axe',
        ['prop'] = 'prop_w_me_hatchet',
        ['hash'] = GetHashKey('prop_w_me_hatchet'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.09,
            ['Y'] = 0.03,
            ['Z'] = -0.02,
            ['XR'] = -78.0,
            ['YR'] = 13.0,
            ['ZR'] = 28.0,
        },
    },
    ['Pickaxe'] = {
        ['name'] = 'Pickaxe',
        ['prop'] = 'prop_tool_pickaxe',
        ['hash'] = GetHashKey('prop_tool_pickaxe'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.09,
            ['Y'] = 0.03,
            ['Z'] = -0.02,
            ['XR'] = -78.0,
            ['YR'] = 13.0,
            ['ZR'] = 28.0,
        },
    },
    ['Drill'] = {
        ['name'] = 'Drill Boor',
        ['prop'] = 'hei_prop_heist_drill',
        ['hash'] = GetHashKey('hei_prop_heist_drill'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.14,
            ['Y'] = 0.0,
            ['Z'] = -0.01,
            ['XR'] = 90.0,
            ['YR'] = -90.0,
            ['ZR'] = 180.0,
        },
    },
    ['Duffel'] = {
        ['name'] = 'DuffelBag',
        ['prop'] = 'xm_prop_x17_bag_01a',
        ['hash'] = GetHashKey('xm_prop_x17_bag_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.27,
            ['Y'] = 0.15,
            ['Z'] = 0.05,
            ['XR'] = 35.0,
            ['YR'] = -125.0,
            ['ZR'] = 50.0,
        },
    },
    ['Cup'] = {
        ['name'] = 'Papieren Beker',
        ['prop'] = 'prop_cs_paper_cup',
        ['hash'] = GetHashKey('prop_cs_paper_cup'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['FishingRod'] = {
        ['name'] = 'Vis Hengel',
        ['prop'] = 'prop_fishing_rod_01',
        ['hash'] = GetHashKey('prop_fishing_rod_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.08,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = -100.0,
            ['YR'] = 0.0,
            ['ZR'] = -20.0,
        },
    },
    ['Boombox'] = {
        ['name'] = 'Boombox',
        ['prop'] = 'prop_boombox_01',
        ['hash'] = GetHashKey('prop_boombox_01'),
        ['bone-index'] = {
            ['bone'] = 1,
            ['X'] = 1,
            ['Y'] = 1,
            ['Z'] = 1,
            ['XR'] = 1,
            ['YR'] = 1,
            ['ZR'] = 1,
        },
    },
    ['Pills'] = {
        ['name'] = 'Pillen',
        ['prop'] = 'prop_cs_pills',
        ['hash'] = GetHashKey('prop_cs_pills'),
        ['bone-index'] = {
            ['bone'] = 1,
            ['X'] = 1,
            ['Y'] = 1,
            ['Z'] = 1,
            ['XR'] = 1,
            ['YR'] = 1,
            ['ZR'] = 1,
        },
    },
    ['ShoppingBag'] = {
        ['name'] = 'Shop Tassen',
        ['prop'] = 'prop_shopping_bags01', 
        ['hash'] = GetHashKey('prop_shopping_bags01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.05,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 35.0,
            ['YR'] = -125.0,
            ['ZR'] = 0.0,
        },
    },
    ['CrackPipe'] = {
        ['name'] = 'Crack Pijp',
        ['prop'] = 'prop_cs_crackpipe',
        ['hash'] = GetHashKey('prop_cs_crackpipe'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.05,
            ['Z'] = 0.0,
            ['XR'] = 135.0,
            ['YR'] = -100.0,
            ['ZR'] = 0.0,
        },
    },
    ['Bong'] = {
        ['name'] = 'Bongetje',
        ['prop'] = 'prop_bong_01',
        ['hash'] = GetHashKey('prop_bong_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.11,
            ['Y'] = -0.23,
            ['Z'] = 0.01,
            ['XR'] = -90.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['slivova'] = {
        ['name'] = 'Slivova',
        ['prop'] = 'prop_drink_whisky',
        ['hash'] = GetHashKey('prop_drink_whisky'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.01,
            ['Z'] = -0.06,
            ['XR'] = 0.0,
            ['YR'] = 0.00,
            ['ZR'] = 0.0,
        },
    },
    ['ovcharskasalata'] = {
        ['name'] = 'ovcharskasalata',
        ['prop'] = 'prop_cs_bowl_01',
        ['hash'] = GetHashKey('prop_cs_bowl_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.050,
            ['XR'] = 0.0,
            ['YR'] = 0.00,
            ['ZR'] = 0.0,
        },
    },
    ['HealthPack'] = {
        ['name'] = 'EHBO Kit',
        ['prop'] = 'prop_ld_health_pack',
        ['hash'] = GetHashKey('prop_ld_health_pack'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.15,
            ['Y'] = 0.08,
            ['Z'] = 0.1,
            ['XR'] = 180.0,
            ['YR'] = 220.0,
            ['ZR'] = 0.0,
        },
    },
    ['ReporterCam'] = {
        ['name'] = 'Weazel News Camera',
        ['prop'] = 'prop_v_cam_01',
        ['hash'] = GetHashKey('prop_v_cam_01'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.13,
            ['Y'] = 0.25,
            ['Z'] = -0.03,
            ['XR'] = -85.0,
            ['YR'] = 0.0,
            ['ZR'] = -80.0,
        },
    },
    ['ReporterMic'] = {
        ['name'] = 'Weazel News Mic',
        ['prop'] = 'p_ing_microphonel_01',
        ['hash'] = GetHashKey('p_ing_microphonel_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.1,
            ['Y'] = 0.05,
            ['Z'] = 0.0,
            ['XR'] = -85.0,
            ['YR'] = -80.0,
            ['ZR'] = -80.0,
        },
    },
    ['BriefCase'] = {
        ['name'] = 'Koffer',
        ['prop'] = 'prop_ld_case_01',
        ['hash'] = GetHashKey('prop_ld_case_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.09,
            ['Y'] = -0.012,
            ['Z'] = 0.01,
            ['XR'] = 320.0,
            ['YR'] = -100.0,
            ['ZR'] = 0.0,
        },
    },
    ['GunCase'] = {
        ['name'] = 'Een wapen koffer',
        ['prop'] = 'prop_box_guncase_01a',
        ['hash'] = GetHashKey('prop_box_guncase_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.18,
            ['Y'] = 0.05,
            ['Z'] = 0.0,
            ['XR'] = 215.0,
            ['YR'] = -175.0,
            ['ZR'] = 100.0,
        },
    },
    ['Box'] = {
        ['name'] = 'Box',
        ['prop'] = 'hei_prop_heist_box',
        ['hash'] = GetHashKey('hei_prop_heist_box'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = 0.025,
            ['Y'] = 0.08,
            ['Z'] = 0.255,
            ['XR'] = -145.0,
            ['YR'] = 290.0,
            ['ZR'] = 0.0,
        },
    },
    ['Tablet'] = {
        ['name'] = 'Een politie tablet',
        ['prop'] = 'prop_cs_tablet',
        ['hash'] = GetHashKey('prop_cs_tablet'),
        ['bone-index'] = {
            ['bone'] = 60309,
            ['X'] = 0.03,
            ['Y'] = 0.002,
            ['Z'] = -0.0,
            ['XR'] = 0.0,
            ['YR'] = 160.0,
            ['ZR'] = 0.0,
        },
    }, 
    ['StolenTv'] = {
        ['name'] = 'Een tv',
        ['prop'] = 'prop_tv_flat_02',
        ['hash'] = GetHashKey('prop_tv_flat_02'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
    ['StolenPc'] = {
        ['name'] = 'Een computer',
        ['prop'] = 'prop_dyn_pc_02',
        ['hash'] = GetHashKey('prop_dyn_pc_02'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.15,
            ['Y'] = 0.10,
            ['Z'] = -0.22,
            ['XR'] = -80.00,
            ['YR'] = -15.00,
            ['ZR'] = -60.00,
        },
    },
    ['StolenMicro'] = {
        ['name'] = 'Een magnetron',
        ['prop'] = 'prop_microwave_1',
        ['hash'] = GetHashKey('prop_microwave_1'),
        ['bone-index'] = {
            ['bone'] = 57005,
            ['X'] = 0.30,
            ['Y'] = 0.15,
            ['Z'] = -0.20,
            ['XR'] = -50.00,
            ['YR'] = 250.00,
            ['ZR'] = 10.00,
        },
    },
    -- Food Props
    ['hamburger'] = {
        ['name'] = 'Broodje Hamburger',
        ['prop'] = 'prop_cs_burger_01',
        ['hash'] = GetHashKey('prop_cs_burger_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.07,
            ['Z'] = 0.02,
            ['XR'] = 120.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['sandwich'] = {
        ['name'] = 'Sandwich',
        ['prop'] = 'prop_sandwich_01',
        ['hash'] = GetHashKey('prop_sandwich_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.02,
            ['XR'] = -50.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['chocolade'] = {
        ['name'] = 'Chocolade',
        ['prop'] = 'prop_choc_meto',
        ['hash'] = GetHashKey('prop_choc_meto'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.01,
            ['XR'] = -50.0,
            ['YR'] = 86.0,
            ['ZR'] = -110.0,
        },
    },
    ['donut'] = {
        ['name'] = 'Donut',
        ['prop'] = 'prop_donut_02',
        ['hash'] = GetHashKey('prop_donut_02'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.16,
            ['Y'] = 0.06,
            ['Z'] = 0.02,
            ['XR'] = 110.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['taco'] = {
        ['name'] = 'Tacootje',
        ['prop'] = 'prop_taco_01',
        ['hash'] = GetHashKey('prop_taco_01'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.07,
            ['Z'] = 0.02,
            ['XR'] = 160.0,
            ['YR'] = 0.0,
            ['ZR'] = -50.0,
        },
    },
    ['burger-fries'] = {
        ['name'] = 'Frietekes',
        ['prop'] = 'prop_food_bs_chips',
        ['hash'] = GetHashKey('prop_food_bs_chips'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.12,
            ['Y'] = 0.04,
            ['Z'] = 0.05,
            ['XR'] = 130.0,
            ['YR'] = 8.0,
            ['ZR'] = 200.0,
        },
    },
    -- Drink Props
    ['cup2'] = {
        ['name'] = 'Plastic Cup',
        ['prop'] = 'prop_plastic_cup_02',
        ['hash'] = GetHashKey('prop_plastic_cup_02'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.01,
            ['Y'] = -0.01,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['water'] = {
        ['name'] = 'Water',
        ['prop'] = 'vw_prop_casino_water_bottle_01a',
        ['hash'] = GetHashKey('vw_prop_casino_water_bottle_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.05,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['coffee'] = {
        ['name'] = 'KOFFIEEE',
        ['prop'] = 'p_amb_coffeecup_01',
        ['hash'] = GetHashKey('p_amb_coffeecup_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['bcoffee'] = {
        ['name'] = 'Bean Machne Coffee',
        ['prop'] = 'prop_fib_coffee',
        ['hash'] = GetHashKey('prop_fib_coffee'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['bcoffee2'] = {
        ['name'] = 'Bean Machne Coffee2',
        ['prop'] = 'ng_proc_coffee_01a',
        ['hash'] = GetHashKey('ng_proc_coffee_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.05,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['orangotang'] = {
        ['name'] = 'Can of Orangotang',
        ['prop'] = 'prop_orang_can_01',
        ['hash'] = GetHashKey('prop_orang_can_01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['sprunk'] = {
        ['name'] = 'Can of Sprunks',
        ['prop'] = 'v_res_tt_can03',
        ['hash'] = GetHashKey('v_res_tt_can03'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['cola'] = {
        ['name'] = 'Lekker blikkie cola',
        ['prop'] = 'prop_ecola_can',
        ['hash'] = GetHashKey('prop_ecola_can'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['burger-soft'] = {
        ['name'] = 'Soft Drink',
        ['prop'] = 'ng_proc_sodacup_01a',
        ['hash'] = GetHashKey('ng_proc_sodacup_01a'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.07,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['burger-ecola'] = {
        ['name'] = 'Ecola Medium',
        ['prop'] = 'v_62_ecolacup002',
        ['hash'] = GetHashKey('v_62_ecolacup002'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.07,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['burger-ecolalight'] = {
        ['name'] = 'Ecola Light',
        ['prop'] = 'v_62_ecolacup01',
        ['hash'] = GetHashKey('v_62_ecolacup01'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.07,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['burger-drink'] = {
        ['name'] = 'Burger Shot Cup',
        ['prop'] = 'prop_cs_bs_cup',
        ['hash'] = GetHashKey('prop_cs_bs_cup'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.07,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['uwu-small-drink'] = {
        ['name'] = 'UwU Smal Drink',
        ['prop'] = 'uwu_sml_drink',
        ['hash'] = GetHashKey('uwu_sml_drink'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['uwu-biscuit'] = {
        ['name'] = 'UwU Biscuit',
        ['prop'] = 'uwu_pastry',
        ['hash'] = GetHashKey('uwu_pastry'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.15,
            ['Y'] = 0.06,
            ['Z'] = -0.02,
            ['XR'] = -50.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['uwu-sushi'] = {
        ['name'] = 'UwU Sushi',
        ['prop'] = 'uwu_sushi',
        ['hash'] = GetHashKey('uwu_sushi'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.15,
            ['Y'] = 0.06,
            ['Z'] = -0.02,
            ['XR'] = -50.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['uwu-eggroll'] = {
        ['name'] = 'UwU Eggroll',
        ['prop'] = 'uwu_eggroll',
        ['hash'] = GetHashKey('uwu_eggroll'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.13,
            ['Y'] = 0.05,
            ['Z'] = 0.02,
            ['XR'] = -50.0,
            ['YR'] = 50.0,
            ['ZR'] = 0.0,
        },
    },
    ['uwu-cup-straw'] = {
        ['name'] = 'UwU 6',
        ['prop'] = 'uwu_cup_straw',
        ['hash'] = GetHashKey('uwu_cup_straw'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = -0.03,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 270.0,
        },
    },
    ['uwu-large-drink'] = {
        ['name'] = 'UwU Large Drink',
        ['prop'] = 'uwu_lrg_drink',
        ['hash'] = GetHashKey('uwu_lrg_drink'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.02,
            ['Y'] = 0.0,
            ['Z'] = -0.06,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 90.0,
        },
    },
    ['uwu-mug'] = {
        ['name'] = 'UwU Mug',
        ['prop'] = 'uwu_mug',
        ['hash'] = GetHashKey('uwu_mug'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 130.0,
        },
    },
    ['uwu-cookie'] = {
        ['name'] = 'UwU Cookie',
        ['prop'] = 'uwu_cookie',
        ['hash'] = GetHashKey('uwu_cookie'),
        ['bone-index'] = { -- {0.16, 0.08, -0.01, -225.0, 20.0, 60.0}
            ['bone'] = 18905,
            ['X'] = 0.16,
            ['Y'] = 0.08,
            ['Z'] = -0.01,
            ['XR'] = -225.0,
            ['YR'] = 20.0,
            ['ZR'] = 60.0,
        },
    },
    ['uwu-donut'] = {
        ['name'] = 'UWU Donut',
        ['prop'] = 'uwu_donut',
        ['hash'] = GetHashKey('uwu_donut'),
        ['bone-index'] = {
            ['bone'] = 18905,
            ['X'] = 0.16,
            ['Y'] = 0.06,
            ['Z'] = 0.02,
            ['XR'] = 110.0,
            ['YR'] = 16.0,
            ['ZR'] = 60.0,
        },
    },
    ['uwu-miso'] = {
        ['name'] = 'UWU Miso',
        ['prop'] = 'uwu_miso',
        ['hash'] = GetHashKey('uwu_miso'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
    ['uwu-eggroll'] = {
        ['name'] = 'UWU Eggroll',
        ['prop'] = 'uwu_eggroll',
        ['hash'] = GetHashKey('uwu_eggroll'),
        ['bone-index'] = {
            ['bone'] = 28422,
            ['X'] = 0.0,
            ['Y'] = 0.0,
            ['Z'] = 0.0,
            ['XR'] = 0.0,
            ['YR'] = 0.0,
            ['ZR'] = 0.0,
        },
    },
}
